# Builds a release version of the project and uploads 
# as artifacts of the release for verification/history

name: release-artifacts
on:
  release:
    types: [published]

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: 🏷 current
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: ⚙ dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: 🙏 build
        run: dotnet build -m:1 -p:version=${GITHUB_REF#refs/*/v}

      - name: 🧪 test
        uses: ./.github/workflows/test

      - name: 📦 pack
        run: dotnet pack -m:1 -p:version=${GITHUB_REF#refs/*/v}

      - name: 🔽 gh 
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: 🔼 artifacts 
        shell: pwsh
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gci .\bin -Recurse -Filter *.nupkg | %{ gh release upload --clobber $env:CURRENT_TAG $_ }