// <autogenerated />
namespace Devlooped.Sponsors;

public static class SponsorStatusExtensions
{
    /// <summary>
    /// Whether represents a sponsor (directly or indirectly).
    /// </summary>
    public static bool IsSponsor(this SponsorStatus status)
        => status == SponsorStatus.User || 
           status == SponsorStatus.Team || 
           status == SponsorStatus.Contributor || 
           status == SponsorStatus.Organization;
}

/// <summary>
/// The determined sponsoring status.
/// </summary>
public enum SponsorStatus
{
    /// <summary>
    /// Sponsorship status is unknown.
    /// </summary>
    Unknown,
    /// <summary>
    /// Sponsorship status is unknown, but within the grace period.
    /// </summary>
    Grace,
    /// <summary>
    /// The sponsors manifest is expired but within the grace period.
    /// </summary>
    Expiring,
    /// <summary>
    /// The sponsors manifest is expired and outside the grace period.
    /// </summary>
    Expired,
    /// <summary>
    /// The user is personally sponsoring.
    /// </summary>
    User,
    /// <summary>
    /// The user is a team member.
    /// </summary>
    Team,
    /// <summary>
    /// The user is a contributor.
    /// </summary>
    Contributor,
    /// <summary>
    /// The user is a member of a contributing organization.
    /// </summary>
    Organization,
    /// <summary>
    /// The user is a OSS author.
    /// </summary>
    OpenSource,
}
